from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import re
import os

def clean_text(text: str) -> str:
    # Remove markdown symbols
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s?', '', text)
    text = re.sub(r'🟢|🟡|🔴|✅|📝|📚|🛡️|🔍|💾|⚙️|👋', '', text)
    text = text.replace('---', '')
    return text.strip()

def export_to_pdf(query: str, summary: str, citations: str, credibility: str, validation: str) -> str:
    filename = f"quria_research_{query[:30].replace(' ', '_')}.pdf"
    filepath = os.path.join("exports", filename)
    os.makedirs("exports", exist_ok=True)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=0.8*inch,
        leftMargin=0.8*inch,
        topMargin=1*inch,
        bottomMargin=0.8*inch
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=22,
        textColor=colors.HexColor('#00C896'),
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#888888'),
        spaceAfter=20,
        fontName='Helvetica'
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#00C896'),
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold'
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#333333'),
        spaceAfter=6,
        leading=16,
        fontName='Helvetica'
    )

    story = []

    # Header
    story.append(Paragraph("QURIA", title_style))
    story.append(Paragraph("Research Intelligence Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#00C896')))
    story.append(Spacer(1, 12))

    # Query
    story.append(Paragraph(f"Research Query: {query}", heading_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cccccc')))
    story.append(Spacer(1, 8))

    # Summary
    story.append(Paragraph("Summary", heading_style))
    for line in clean_text(summary).split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
    story.append(Spacer(1, 8))

    # Citations
    story.append(Paragraph("Citations", heading_style))
    for line in clean_text(citations).split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
    story.append(Spacer(1, 8))

    # Credibility
    story.append(Paragraph("Source Credibility", heading_style))
    for line in clean_text(credibility).split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
    story.append(Spacer(1, 8))

    # Validation
    story.append(Paragraph("Validation", heading_style))
    for line in clean_text(validation).split('\n'):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#00C896')))
    story.append(Paragraph("Generated by Quria — Research Intelligence", subtitle_style))

    doc.build(story)
    return filepath